---
- name: Configure Apache on RHEL server Andra
  hosts: webserver
  become: true

  tasks:
    - name: Ensure python3-firewall is installed for firewalld module
      ansible.builtin.dnf:
        name: python3-firewall
        state: present
      when: ansible_facts['distribution'] == 'RedHat'

    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Configure firewall to allow HTTP (port 80)
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_facts['distribution'] == 'RedHat'